### PR TITLE
Add support for TypeScript

### PR DESCRIPTION
**Pull request by realmunk**
- Add native support for TypeScript
- Add examples for test

### CODE REVIEW

**Comment by espen42** [comment]
@rymsha, did you mean this should be re-opened?

**Comment by rymsha** [comment]
@espen42 You can't reopen something already open :)

Maybe you should close it?

**Comment by espen42** [comment]
Will be handled as part of: https://github.com/enonic/lib-react4xp/issues/103 and https://github.com/enonic/lib-react4xp/issues/105

**Comment by espen42** [comment]
Will be handled as part of: enonic/lib-react4xp#103 and enonic/lib-react4xp#105

**Pull request closed without merging**
